import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, Stars, Line } from '@react-three/drei';
import * as THREE from 'three';
import './styles.css';

const KEY='orbital-v03-neo';
const MISSIONS={
 'LEO-01':{name:'LOW-EARTH OBSERVATION',tag:'LEO / EARTH SCIENCE',brief:'Operate a small observation spacecraft in low Earth orbit. Your job is to stabilize the vehicle, deploy power, establish communications, acquire a target and complete three orbital passes.',alt:542,inc:51.6,fuel:72,objectives:[['stabilize','Set attitude to NADIR','Point the spacecraft toward Earth for observation.'],['solar','Deploy solar arrays','Generate electrical power for the spacecraft.'],['comms','Point communications antenna','Create a reliable link to the ground station.'],['target','Acquire observation target','Lock the payload onto the assigned region.'],['passes','Complete 3 orbital passes','Keep the spacecraft operating until three passes are logged.']]},
 'POLAR-02':{name:'POLAR SCAN',tag:'HIGH INCLINATION',brief:'Fly a high-inclination orbit and prepare the payload to scan a polar corridor while maintaining power and communications.',alt:720,inc:87.4,fuel:82,objectives:[['stabilize','Set attitude to NADIR','NADIR keeps the observation payload pointed toward Earth.'],['solar','Deploy solar arrays','Power generation is essential during long mission operations.'],['comms','Point communications antenna','Telemetry is the spacecraft status sent to the ground.'],['target','Acquire polar target','The payload must lock onto the requested scan corridor.'],['passes','Complete 3 orbital passes','A pass is one trip around the selected orbit.']]},
 'LUNAR-03':{name:'LUNAR TRANSFER',tag:'DEEP-SPACE PREP',brief:'Prepare a transfer profile, configure spacecraft power and communications, then obtain a navigation lock before completing the mission sequence.',alt:1100,inc:28.5,fuel:96,objectives:[['stabilize','Set attitude to PROGRADE','PROGRADE points the spacecraft along its direction of travel.'],['solar','Deploy solar arrays','Power margins matter more as the mission leaves low Earth orbit.'],['comms','Point communications antenna','Antenna pointing keeps the ground link available.'],['target','Acquire navigation lock','A navigation lock confirms the spacecraft solution is usable.'],['passes','Complete 3 orbital passes','Practice reading the orbit before a future transfer burn.']]}
};
const KNOW={
 stabilize:{title:'WHY ATTITUDE MATTERS',text:'Spacecraft do not steer like cars. Attitude controls rotate the vehicle so sensors, antennas and solar arrays point where they need to point.',control:'NADIR / PROGRADE / RETROGRADE',action:'Choose the attitude that matches the mission objective. NADIR points toward Earth, PROGRADE points along travel, and RETROGRADE points opposite travel.'},
 solar:{title:'POWER LESSON',text:'Solar arrays turn sunlight into electrical power. Deploying them increases the spacecraft power margin and supports longer operations.',control:'SOLAR ARRAY',action:'Press SOLAR ARRAY once to deploy it. Press it again to stow it.'},
 comms:{title:'TELEMETRY LESSON',text:'Telemetry is spacecraft status sent to the ground: power, temperature, fuel, signal and other measurements.',control:'ANTENNA',action:'Press ANTENNA to point the communications system and establish the mission link.'},
 target:{title:'PAYLOAD LESSON',text:'A payload is the mission hardware that performs the useful job. Observation missions need accurate pointing before collecting data.',control:'PAYLOAD',action:'Press PAYLOAD to acquire the assigned observation or navigation target.'},
 passes:{title:'ORBIT LESSON',text:'An orbital pass is one trip around the central body. Higher orbits generally have longer orbital periods.',control:'START MISSION',action:'Press START MISSION after configuring the spacecraft. Keep the mission running until PASS reaches 3/3.'}
};
function velocity(a){return Math.sqrt(398600.4418/(6371+a));}
function period(a){return 2*Math.PI*Math.sqrt(Math.pow(6371+a,3)/398600.4418)/60;}
function id(){return 'THZ-ORB-'+Date.now().toString(36).slice(-7).toUpperCase();}
function Scene({alt,inc,angle,target}){const earth=useRef();const r=2.15+Math.max(0,alt-250)/1200*1.2;const rad=THREE.MathUtils.degToRad(inc);useFrame((_,d)=>{if(earth.current)earth.current.rotation.y+=d*.035});const pts=useMemo(()=>Array.from({length:181},(_,i)=>{const a=i/180*Math.PI*2;return[r*Math.cos(a),r*Math.sin(a)*Math.sin(rad),r*Math.sin(a)*Math.cos(rad)]}),[r,rad]);const sat=[r*Math.cos(angle),r*Math.sin(angle)*Math.sin(rad),r*Math.sin(angle)*Math.cos(rad)];return <><color attach="background" args={['#101010']}/><ambientLight intensity={.35}/><directionalLight position={[5,4,5]} intensity={2.4}/><Stars radius={90} depth={45} count={3500} factor={1.7} fade speed={.2}/><mesh ref={earth}><sphereGeometry args={[2.05,48,48]}/><meshStandardMaterial color="#1c8cff" roughness={.9}/></mesh><Line points={pts} color="#f5d90a" lineWidth={2}/>{target&&<Line points={pts.map(p=>p.map(v=>v*1.018))} color="#ff4d6d" lineWidth={2}/>}<group position={sat}><mesh><boxGeometry args={[.26,.2,.35]}/><meshStandardMaterial color="#fff"/></mesh><mesh position={[.43,0,0]}><boxGeometry args={[.58,.025,.26]}/><meshStandardMaterial color="#ffcc00"/></mesh><mesh position={[-.43,0,0]}><boxGeometry args={[.58,.025,.26]}/><meshStandardMaterial color="#ffcc00"/></mesh></group></>}
function App(){
 const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}},[]);const [mission,setMission]=useState(saved?.mission||'LEO-01');const [tab,setTab]=useState('MISSION');const [running,setRunning]=useState(false);const [complete,setComplete]=useState(saved?.complete||false);const [seconds,setSeconds]=useState(saved?.seconds||0);const [angle,setAngle]=useState(saved?.angle||.2);const [fuel,setFuel]=useState(saved?.fuel??MISSIONS[mission].fuel);const [battery,setBattery]=useState(saved?.battery??82);const [signal,setSignal]=useState(saved?.signal??92);const [temp,setTemp]=useState(saved?.temp??24);const [passes,setPasses]=useState(saved?.passes||0);const [attitude,setAttitude]=useState(saved?.attitude||'NOMINAL');const [solar,setSolar]=useState(saved?.solar||false);const [comms,setComms]=useState(saved?.comms||false);const [target,setTarget]=useState(saved?.target||false);const [knowledge,setKnowledge]=useState(saved?.knowledge||'stabilize');const [certName,setCertName]=useState(saved?.certName==='Ragul'?'':(saved?.certName||''));const [certId,setCertId]=useState(saved?.certId||id());const [savedAt,setSavedAt]=useState(saved?.savedAt||'—');const [secret,setSecret]=useState(false);const logoClicks=useRef(0);const timer=useRef();const m=MISSIONS[mission];
 const objectiveDone=[attitude!=='NOMINAL',solar,comms,target,passes>=3];const doneCount=objectiveDone.filter(Boolean).length;const pct=doneCount/5*100;const speed=velocity(m.alt);const orbPeriod=period(m.alt);
 useEffect(()=>{if(!running||complete)return;const t=setInterval(()=>{setSeconds(s=>s+1);setAngle(a=>{const n=(a+speed/60*.08)%(Math.PI*2);if(n<a&&passes<3)setPasses(p=>Math.min(3,p+1));return n});setFuel(f=>Math.max(0,+((f-.012)).toFixed(2)));setBattery(b=>Math.max(0,+((b+(solar?.035:.012)-.012)).toFixed(2)));setSignal(s=>Math.max(45,Math.min(100,+(s+(Math.random()-.5)*1.8).toFixed(1))));setTemp(x=>+(x+(solar?-0.01:.03)+(Math.random()-.5)*.18).toFixed(1))},1000);return()=>clearInterval(t)},[running,complete,speed,solar,passes]);
 useEffect(()=>{if(doneCount===5&&!complete){setComplete(true);setRunning(false)}},[doneCount,complete]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({mission,complete,seconds,angle,fuel,battery,signal,temp,passes,attitude,solar,comms,target,knowledge,certName,certId,savedAt}))},[mission,complete,seconds,angle,fuel,battery,signal,temp,passes,attitude,solar,comms,target,knowledge,certName,certId,savedAt]);
 const learn=k=>{setKnowledge(k);setTab('MISSION')};
 const reset=(missionKey=mission)=>{clearInterval(timer.current);const x=MISSIONS[missionKey];setRunning(false);setComplete(false);setSeconds(0);setAngle(.2);setFuel(x.fuel);setBattery(82);setSignal(92);setTemp(24);setPasses(0);setAttitude('NOMINAL');setSolar(false);setComms(false);setTarget(false);setKnowledge('stabilize');setSavedAt('—');setCertId(id())};
 const save=()=>{setSavedAt(new Date().toLocaleTimeString());};
 const cheat=()=>{setComplete(true);setRunning(false);setAttitude('OVERRIDE');setSolar(true);setComms(true);setTarget(true);setPasses(3);setSavedAt(new Date().toLocaleTimeString());setTab('CERTIFICATE');setSecret(false)};
 const clickLogo=()=>{logoClicks.current++;clearTimeout(timer.current);timer.current=setTimeout(()=>logoClicks.current=0,1300);if(logoClicks.current>=5){logoClicks.current=0;setSecret(true)}};
 const changeMission=e=>{const key=e.target.value;setMission(key);reset(key)};
 return <div className="app">
  <header className="top"><button className="brand" onClick={clickLogo} aria-label="THIRAZEN"><span className="brand-mark">T</span><span><b>THIRAZEN</b><small>MISSION LAB / LEARN • BUILD • BECOME</small></span></button><div className="orbit-name"><strong>ORBITAL</strong><span>MISSION SIMULATOR</span></div><div className="status"><i/> SIMULATION ONLINE</div></header>
  <nav className="tabs">{['MISSION','CONFIGURATION','CERTIFICATE'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button className="reset" onClick={reset}>↻ RESET MISSION</button></nav>
  {tab==='MISSION'&&<main className="mission-layout">
   <section className="left">
    <div className="mission-intro"><div className="kicker">YOUR MISSION</div><h1>{m.name}</h1><p>{m.brief}</p><div className="mission-rule"><b>WHAT TO DO</b><span>Complete the five objectives in order. Use the named control for each step; the Flight School panel explains what the control does while you operate.</span></div></div>
    <div className="orbit-card"><Canvas camera={{position:[6,4,6],fov:45}}><Scene alt={m.alt} inc={m.inc} angle={angle} target={target}/><OrbitControls enablePan={false} minDistance={4} maxDistance={12}/></Canvas><div className="orbit-hud"><span>ALT {m.alt} KM</span><span>INC {m.inc}°</span><span>PASS {passes}/3</span></div></div>
   </section>
   <aside className="control-column">
    <div className="neo-card objective-card"><div className="card-head"><b>MISSION CHECKLIST</b><strong>{doneCount}/5</strong></div>{m.objectives.map(([key,label])=><button className={'objective '+(objectiveDone[['stabilize','solar','comms','target','passes'].indexOf(key)]?'done':'')} key={key} onClick={()=>learn(key)}><span>{objectiveDone[['stabilize','solar','comms','target','passes'].indexOf(key)]?'✓':'□'}</span><b>{label}</b><em>{objectiveDone[['stabilize','solar','comms','target','passes'].indexOf(key)]?'COMPLETE':'LEARN →'}</em></button>)}<div className="progress"><i style={{width:pct+'%'}}/></div></div>
    <div className="neo-card controls"><div className="card-head"><b>SPACECRAFT CONTROLS</b><span>LIVE</span></div><div className="control-grid"><button className={attitude==='NADIR'?'selected':''} onClick={()=>{setAttitude('NADIR');learn('stabilize')}}>NADIR<small>EARTH POINT</small></button><button className={attitude==='PROGRADE'?'selected':''} onClick={()=>{setAttitude('PROGRADE');learn('stabilize')}}>PROGRADE<small>TRAVEL VECTOR</small></button><button className={attitude==='RETROGRADE'?'selected':''} onClick={()=>{setAttitude('RETROGRADE');learn('stabilize')}}>RETROGRADE<small>BRAKE VECTOR</small></button><button className={solar?'selected':''} onClick={()=>{setSolar(x=>!x);learn('solar')}}>SOLAR ARRAY<small>{solar?'DEPLOYED':'DEPLOY'}</small></button><button className={comms?'selected':''} onClick={()=>{setComms(x=>!x);learn('comms')}}>ANTENNA<small>{comms?'LOCKED':'POINT'}</small></button><button className={target?'selected':''} onClick={()=>{setTarget(x=>!x);learn('target')}}>PAYLOAD<small>{target?'TARGET LOCK':'ACQUIRE'}</small></button></div><div className="run-row"><button onClick={()=>setRunning(x=>!x)} className="go">{running?'PAUSE':'START MISSION'}</button><button onClick={save}>SAVE</button></div></div>
    <div className="neo-card knowledge"><div className="knowledge-top"><b>FLIGHT SCHOOL</b><span>LEARN WHILE YOU FLY</span></div><h2>{KNOW[knowledge].title}</h2><p>{KNOW[knowledge].text}</p><div className="how-control"><b>CONTROL TO USE</b><strong>{KNOW[knowledge].control}</strong><span>{KNOW[knowledge].action}</span></div><div className="fact"><b>QUICK FACT</b> {m.tag==='LEO / EARTH SCIENCE'?`This orbit takes about ${orbPeriod.toFixed(1)} minutes per revolution.`:'Your current orbit is '+m.alt+' km above Earth.'}</div></div>
    <div className="telemetry neo-card"><div className="card-head"><b>TELEMETRY</b><span>{seconds}s</span></div><div className="tele-grid"><div>FUEL<strong>{fuel.toFixed(1)}%</strong></div><div>BATTERY<strong>{battery.toFixed(1)}%</strong></div><div>SIGNAL<strong>{signal.toFixed(0)}%</strong></div><div>TEMP<strong>{temp.toFixed(1)}°C</strong></div></div></div>
   </aside>
  </main>}
  {tab==='CONFIGURATION'&&<main className="config-page"><div className="neo-card big"><div className="kicker">MISSION CONFIGURATION</div><h1>BUILD YOUR FLIGHT</h1><p>Choose a scenario. Configuration changes the learning context and spacecraft profile; the mission itself is completed through actions, not just a button press.</p><label>MISSION<select value={mission} onChange={changeMission}>{Object.entries(MISSIONS).map(([k,x])=><option key={k} value={k}>{k} — {x.name}</option>)}</select></label><div className="config-info"><span>ALTITUDE <b>{m.alt} km</b></span><span>INCLINATION <b>{m.inc}°</b></span><span>FUEL <b>{m.fuel}%</b></span></div><button className="big-button" onClick={()=>setTab('MISSION')}>APPLY & ENTER MISSION →</button></div><div className="neo-card big"><div className="kicker">HOW IT WORKS</div><h2>LEARN BY OPERATING</h2><ol><li>Read the mission brief.</li><li>Choose a spacecraft control.</li><li>See the lesson update instantly.</li><li>Complete all five objectives.</li><li>Customize and generate your certificate.</li></ol></div></main>}
  {tab==='CERTIFICATE'&&<main className="certificate-page"><div className="neo-card cert-controls"><div className="kicker">{complete?'MISSION COMPLETE':'CERTIFICATE PREVIEW'}</div><h1>CERTIFICATE LAB</h1>{complete?<p>Your mission record is complete. Enter the recipient name, then print or save the certificate as a single landscape page.</p>:<p>Complete the mission to unlock the personalized certificate. Your name is intentionally blank until you enter it.</p>}<label>RECIPIENT NAME<input value={certName} maxLength={42} placeholder="ENTER RECIPIENT NAME" onChange={e=>setCertName(e.target.value)} disabled={!complete}/></label><div className="cert-meta"><span>MISSION<b>{m.name}</b></span><span>ISSUED<b>{new Date().toLocaleDateString()}</b></span><span>ID<b>{certId}</b></span></div><button className="big-button" disabled={!complete||!certName.trim()} onClick={()=>window.print()}>PRINT / SAVE PDF</button><button className="secondary" onClick={()=>setTab('MISSION')}>← BACK TO MISSION</button>{!complete&&<div className="locked-note">🔒 Certificate editing and printing unlock after mission completion.</div>}</div><div className={'certificate neo-certificate '+(!complete?'certificate-locked':'')}><div className="cert-corner corner-a"/><div className="cert-corner corner-b"/><div className="cert-corner corner-c"/><div className="cert-corner corner-d"/><div className="neo-cert-brand"><img src="./thirazen-logo.png" alt="" className="neo-cert-logo"/><div><b>THIRAZEN</b><small>LEARN • BUILD • BECOME</small></div></div><div className="neo-cert-kicker">MISSION CONTROL ACADEMY</div><h2>CERTIFICATE</h2><div className="neo-cert-subtitle">OF MISSION COMPLETION</div><div className="neo-cert-rule"/><div className="neo-cert-label">THIS IS TO CERTIFY THAT</div><div className="neo-cert-name">{certName.trim()||'RECIPIENT NAME'}</div><div className="neo-cert-body">has successfully completed the mission</div><div className="neo-cert-mission">{m.name}</div><div className="neo-cert-description">Demonstrating successful mission operations, spacecraft control,<br/>telemetry management, and completion of the required objectives.</div><div className="neo-cert-footer"><div><span>ISSUED</span><b>{new Date().toLocaleDateString()}</b></div><div><span>MISSION ID</span><b>{mission}</b></div><div><span>CERTIFICATE ID</span><b>{certId}</b></div><div className="neo-sign"><img src="./ragul-signature.png" alt="Ragul signature"/><span>RAGUL • FOUNDER & CEO • THIRAZEN</span></div></div><div className="neo-seal">T<div>MISSION<br/>COMPLETE</div></div>{!complete&&<div className="certificate-watermark">MISSION NOT YET COMPLETE</div>}</div></main>}
  <footer><span>ORBITAL / THIRAZEN MISSION LAB</span><span>MISSION SIMULATION • LOCAL SAVE</span></footer>
  {secret&&<div className="overlay"><div className="secret-box"><div className="kicker">RESTRICTED SYSTEM</div><h2>MISSION OVERRIDE</h2><p>Maintenance shortcut detected. This will mark every objective complete, save the mission and open the certificate lab.</p><button className="big-button" onClick={cheat}>EXECUTE OVERRIDE</button><button className="secondary" onClick={()=>setSecret(false)}>CANCEL</button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
